### ISSUE TITLE
could be used with older rust by any chance?

### ISSUE THREAD

**Issue by yarikoptic** [jwodder/dandidav#37]
builds fails with

```
error: package `dandidav v0.1.0 (/home/yoh/proj/dandi/dandidav)` cannot be built because it requires rustc 1.74 or newer, while the currently active rustc version is 1.70.0
```

and debian has only

```shell
❯ acpolicy rustc
rustc:
  Installed: 1.70.0+dfsg1-5
  Candidate: 1.70.0+dfsg1-5
  Version table:
 *** 1.70.0+dfsg1-5 900
        600 https://deb.debian.org/debian sid/main amd64 Packages
        900 https://deb.debian.org/debian trixie/main amd64 Packages
        100 /var/lib/dpkg/status
     1.63.0+dfsg1-2 100
        100 https://deb.debian.org/debian bookworm/main amd64 Packages
````

**Comment by jwodder** [comment]
* I initially aimed for an MSRV of 1.70, but it didn't compile on anything pre-1.74.

* It is highly recommended not to install Rust via Apt or other system package managers because such versions are almost invariably out of date.  Install from rustup.rs instead.

**Comment by jwodder** [comment]
@yarikoptic I managed to get this to compile on 1.70.  You haven't already installed the latest Rust, have you?

**Comment by yarikoptic** [comment]
nope -- found other things to entertain myself with interim ;) thanks! I will give it a shot later today!
